# Generated by Django 3.2.11 on 2022-02-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
