# Generated by Django 3.2.11 on 2022-02-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_snippet_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
