# Generated by Django 3.2.11 on 2022-02-16 18:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('original_url', models.URLField(verbose_name='URL Field')),
                ('shorten_url', models.URLField(verbose_name='Shorten URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippet.snippet')),
            ],
        ),
    ]
